spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
     active: usage_message
  #jpa
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update

  #rabitmq连接
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456

    #redis连接
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60s
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
#mybatis配置
mybatis:
    typeAliasesPackage: com.restful.bo
    mapperLocations: classpath:mapping/*.xml

logging:
  config: classpath:log4j2.xml
