spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
     active: usage_message
  #jpa
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  #rabitmq连接
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
#mybatis配置
mybatis:
    typeAliasesPackage: com.restful.bo
    mapperLocations: classpath:mapping/*.xml

#redis连接
redis:
    host: 127.0.0.1
    post: 6379
    password:
    pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1
    timeout: 2000

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000